# * scaleClientDNS
services:
  caddy:
    image: vlad/caddy:0.1.0
    networks:
      - vladnet
  headclient:
    image: vlad/headclient:0.1.0
    environment:
      - HEADCLIENT_CONFIG=/opt/config/headclient.yaml
      - HEADCLIENT_HOST=http://caddy:4321
    secrets:
      - source: headclient-config
        target: /opt/config/headclient.yaml
    networks:
      - vladnet
    depends_on:
      - caddy
secrets:
  headclient-config:
    file: headclient.yaml
networks:
  vladnet: { }
