---
dsn: memory
serve:
  public:
    port: 4444
    tls:
      cert:
        path: /hydra/cert.pem
      key:
        path: /hydra/key.pem
  admin:
    port: 4445
    tls:
      cert:
        path: /hydra/cert.pem
      key:
        path: /hydra/key.pem
urls:
  self:
    public: https://hydra:4444/
    issuer: https://hydra:4444/
strategies:
  # access_token: opaque
  access_token: jwt
ttl:
  access_token: 5m
