// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: productinfo.proto

package ecommerce

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ProductInfo_AddProduct_FullMethodName     = "/ecommerce.ProductInfo/addProduct"
	ProductInfo_GetProduct_FullMethodName     = "/ecommerce.ProductInfo/getProduct"
	ProductInfo_SearchProducts_FullMethodName = "/ecommerce.ProductInfo/searchProducts"
	ProductInfo_UpdateProducts_FullMethodName = "/ecommerce.ProductInfo/updateProducts"
	ProductInfo_GetProducts_FullMethodName    = "/ecommerce.ProductInfo/getProducts"
)

// ProductInfoClient is the client API for ProductInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductInfoClient interface {
	// request-response
	AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductID, error)
	GetProduct(ctx context.Context, in *ProductID, opts ...grpc.CallOption) (*Product, error)
	// server streaming
	SearchProducts(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (ProductInfo_SearchProductsClient, error)
	// client streaming
	UpdateProducts(ctx context.Context, opts ...grpc.CallOption) (ProductInfo_UpdateProductsClient, error)
	// bidirectional streaming
	GetProducts(ctx context.Context, opts ...grpc.CallOption) (ProductInfo_GetProductsClient, error)
}

type productInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewProductInfoClient(cc grpc.ClientConnInterface) ProductInfoClient {
	return &productInfoClient{cc}
}

func (c *productInfoClient) AddProduct(ctx context.Context, in *Product, opts ...grpc.CallOption) (*ProductID, error) {
	out := new(ProductID)
	err := c.cc.Invoke(ctx, ProductInfo_AddProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInfoClient) GetProduct(ctx context.Context, in *ProductID, opts ...grpc.CallOption) (*Product, error) {
	out := new(Product)
	err := c.cc.Invoke(ctx, ProductInfo_GetProduct_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productInfoClient) SearchProducts(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (ProductInfo_SearchProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductInfo_ServiceDesc.Streams[0], ProductInfo_SearchProducts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &productInfoSearchProductsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProductInfo_SearchProductsClient interface {
	Recv() (*Product, error)
	grpc.ClientStream
}

type productInfoSearchProductsClient struct {
	grpc.ClientStream
}

func (x *productInfoSearchProductsClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productInfoClient) UpdateProducts(ctx context.Context, opts ...grpc.CallOption) (ProductInfo_UpdateProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductInfo_ServiceDesc.Streams[1], ProductInfo_UpdateProducts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &productInfoUpdateProductsClient{stream}
	return x, nil
}

type ProductInfo_UpdateProductsClient interface {
	Send(*Product) error
	CloseAndRecv() (*wrapperspb.StringValue, error)
	grpc.ClientStream
}

type productInfoUpdateProductsClient struct {
	grpc.ClientStream
}

func (x *productInfoUpdateProductsClient) Send(m *Product) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productInfoUpdateProductsClient) CloseAndRecv() (*wrapperspb.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrapperspb.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *productInfoClient) GetProducts(ctx context.Context, opts ...grpc.CallOption) (ProductInfo_GetProductsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ProductInfo_ServiceDesc.Streams[2], ProductInfo_GetProducts_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &productInfoGetProductsClient{stream}
	return x, nil
}

type ProductInfo_GetProductsClient interface {
	Send(*ProductID) error
	Recv() (*Product, error)
	grpc.ClientStream
}

type productInfoGetProductsClient struct {
	grpc.ClientStream
}

func (x *productInfoGetProductsClient) Send(m *ProductID) error {
	return x.ClientStream.SendMsg(m)
}

func (x *productInfoGetProductsClient) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductInfoServer is the server API for ProductInfo service.
// All implementations must embed UnimplementedProductInfoServer
// for forward compatibility
type ProductInfoServer interface {
	// request-response
	AddProduct(context.Context, *Product) (*ProductID, error)
	GetProduct(context.Context, *ProductID) (*Product, error)
	// server streaming
	SearchProducts(*wrapperspb.StringValue, ProductInfo_SearchProductsServer) error
	// client streaming
	UpdateProducts(ProductInfo_UpdateProductsServer) error
	// bidirectional streaming
	GetProducts(ProductInfo_GetProductsServer) error
	mustEmbedUnimplementedProductInfoServer()
}

// UnimplementedProductInfoServer must be embedded to have forward compatible implementations.
type UnimplementedProductInfoServer struct {
}

func (UnimplementedProductInfoServer) AddProduct(context.Context, *Product) (*ProductID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProduct not implemented")
}
func (UnimplementedProductInfoServer) GetProduct(context.Context, *ProductID) (*Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductInfoServer) SearchProducts(*wrapperspb.StringValue, ProductInfo_SearchProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchProducts not implemented")
}
func (UnimplementedProductInfoServer) UpdateProducts(ProductInfo_UpdateProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateProducts not implemented")
}
func (UnimplementedProductInfoServer) GetProducts(ProductInfo_GetProductsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedProductInfoServer) mustEmbedUnimplementedProductInfoServer() {}

// UnsafeProductInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductInfoServer will
// result in compilation errors.
type UnsafeProductInfoServer interface {
	mustEmbedUnimplementedProductInfoServer()
}

func RegisterProductInfoServer(s grpc.ServiceRegistrar, srv ProductInfoServer) {
	s.RegisterService(&ProductInfo_ServiceDesc, srv)
}

func _ProductInfo_AddProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).AddProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInfo_AddProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).AddProduct(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInfo_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductInfoServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductInfo_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductInfoServer).GetProduct(ctx, req.(*ProductID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProductInfo_SearchProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(wrapperspb.StringValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProductInfoServer).SearchProducts(m, &productInfoSearchProductsServer{stream})
}

type ProductInfo_SearchProductsServer interface {
	Send(*Product) error
	grpc.ServerStream
}

type productInfoSearchProductsServer struct {
	grpc.ServerStream
}

func (x *productInfoSearchProductsServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

func _ProductInfo_UpdateProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductInfoServer).UpdateProducts(&productInfoUpdateProductsServer{stream})
}

type ProductInfo_UpdateProductsServer interface {
	SendAndClose(*wrapperspb.StringValue) error
	Recv() (*Product, error)
	grpc.ServerStream
}

type productInfoUpdateProductsServer struct {
	grpc.ServerStream
}

func (x *productInfoUpdateProductsServer) SendAndClose(m *wrapperspb.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productInfoUpdateProductsServer) Recv() (*Product, error) {
	m := new(Product)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProductInfo_GetProducts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProductInfoServer).GetProducts(&productInfoGetProductsServer{stream})
}

type ProductInfo_GetProductsServer interface {
	Send(*Product) error
	Recv() (*ProductID, error)
	grpc.ServerStream
}

type productInfoGetProductsServer struct {
	grpc.ServerStream
}

func (x *productInfoGetProductsServer) Send(m *Product) error {
	return x.ServerStream.SendMsg(m)
}

func (x *productInfoGetProductsServer) Recv() (*ProductID, error) {
	m := new(ProductID)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProductInfo_ServiceDesc is the grpc.ServiceDesc for ProductInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ecommerce.ProductInfo",
	HandlerType: (*ProductInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addProduct",
			Handler:    _ProductInfo_AddProduct_Handler,
		},
		{
			MethodName: "getProduct",
			Handler:    _ProductInfo_GetProduct_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "searchProducts",
			Handler:       _ProductInfo_SearchProducts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "updateProducts",
			Handler:       _ProductInfo_UpdateProducts_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "getProducts",
			Handler:       _ProductInfo_GetProducts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "productinfo.proto",
}
