---
serve:
  proxy:
    port: 4455
    tls:
      cert:
        path: /oathkeeper/cert.pem
      key:
        path: /oathkeeper/key.pem
  api:
    port: 4456
    tls:
      cert:
        path: /oathkeeper/cert.pem
      key:
        path: /oathkeeper/key.pem
access_rules:
  repositories: [file://oathkeeper/oathkeeper_rules.yaml]
  matching_strategy: regexp
authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: https://hydra:4445/oauth2/introspect
      trusted_issuers: [https://hydra:4444/]
      scope_strategy: exact
  jwt:
    enabled: true
    config:
      jwks_urls: [https://hydra:4444/.well-known/jwks.json]
      allowed_algorithms: [RS256]
      trusted_issuers: [https://hydra:4444/]
      scope_strategy: exact
authorizers:
  allow:
    enabled: true
mutators:
  noop:
    enabled: true
errors:
  handlers:
    json:
      enabled: true
      config:
        verbose: true
