---
title: Benchmarking analysis report
date: 2021-06-08
---

```{r report-config, include = F}
opts_chunk$set(error = F, dev = "svg")
```

# Executive summary

TODO

# Introduction

TODO

# Benchmarking analysis

## Pricing analysis

### Single node pricing

```{r snp-data}
snp <- data.frame(
  inst.type = c("c5", "c5a", "c5n", "c6g"),
  tps.peak = c(505, 469, 509, 572),
  cost.hour = c(0.77, 0.69, 0.98, 0.61),
  cost.mtx = c(0.42, 0.41, 0.53, 0.30))
```

```{r snp-tps.peak-inst.type, fig.cap = "TPS peak per instance type (single node)"}
ggplot(snp, aes(inst.type, tps.peak,
  color = inst.type, fill = inst.type)) +
  geom_bar(stat = "identity", alpha = 0.2) +
  xlab("Instance type") + ylab("TPS peak")
```

```{r snp-cost.mtx-inst.type, fig.cap = "Cost of 1M TX per instance type (single node)"}
ggplot(snp, aes(inst.type, cost.mtx,
  color = inst.type, fill = inst.type)) +
  geom_bar(stat = "identity", alpha = 0.2) +
  xlab("Instance type") + ylab("Cost of 1M TX")
```

```{r snp-cost.mtx-tps.peak, fig.cap = "TPS peak vs cost of 1M TX per instance type (single node)"}
ggplot(snp, aes(cost.mtx, tps.peak)) +
  geom_point(aes(size = tps.peak, color = tps.peak)) +
  scale_size_continuous(range = c(5, 12)) +
  geom_text(aes(x = cost.mtx, y = tps.peak, label = inst.type),
    hjust = "left", nudge_x = 0.015, size = 5) +
  xlim(0.28, 0.6) + xlab("Cost of 1M TX") + ylab("TPS peak")
```

### Multi-node pricing

```{r mnp-data}
mnp <- data.frame(
  cts.inst.type = c("c5.4xlarge", "c5.4xlarge", "c5.4xlarge", "c5.4xlarge", "c5.4xlarge"),
  cts.inst.num = c(1, 2, 3, 4, 5),
  rt1.inst.type = c("c5.2xlarge", "c5.2xlarge", "c5.2xlarge", "c5.2xlarge", "c5.2xlarge"),
  rt1.inst.num = c(2, 2, 2, 2, 3),
  tps.peak = c(506, 804, 1140, 1510, 1996),
  cost.mtx = c(1.67, 0.99, 0.66, 0.47, 0.35))
```

```{r mnp-cts.inst.num-tps.peak, fig.cap = "TPS peak per CTS instance number"}
ggplot(mnp, aes(cts.inst.num, tps.peak,
    color = factor(cts.inst.num), fill = factor(cts.inst.num))) +
  geom_bar(stat = "identity", alpha = 0.2) +
  xlab("CTS instance number") + ylab("TPS peak")
```

```{r mnp-cts.inst.num-cost.mtx, fig.cap = "Cost of 1M TX per CTS instance number"}
ggplot(mnp, aes(cts.inst.num, cost.mtx,
    color = factor(cts.inst.num), fill = factor(cts.inst.num))) +
  geom_bar(stat = "identity", alpha = 0.2) +
  xlab("CTS instance number") + ylab("Cost of 1M TX")
```

```{r mnp-cost.mtx-tps.peak, fig.cap = "TPS peak vs cost of 1M TX per CTS instance number"}
ggplot(mnp, aes(cost.mtx, tps.peak)) +
  geom_point(aes(size = tps.peak, color = tps.peak)) +
  scale_size_continuous(range = c(5, 12)) +
  xlab("Cost of 1M TX") + ylab("TPS peak")
```

# Conclusions

TODO
