---
title: A minimal Rmd example with ggplot2
author: Volodymyr Prokopyuk
date: `r Sys.Date()`
keywords: [markdown, knitr, literate-programming, ggplot2]
abstract: |
  Markdown and knitr along with ggplot2 make literate programming in R very convenient
css:
  - style/style.css
header-includes:
  - <link rel="shortcut icon" href="image/html5-favicon.png"/>
---

```{r document-config, include = F}
opts_chunk$set(error = F, dev = "svg")
```

```{r exports-data, include = T}
raw_export <- "year,product,export,percentage
2006,copper,4335009500,81
2006,others,1016726518,19
2007,copper,9005361914,86
2007,others,1523085299,14
2008,copper,6907056354,80
2008,others,1762684216,20
2009,copper,10529811075,81
2009,others,2464094241,19
2010,copper,14828284450,85
2010,others,2543015596,15
2011,copper,15291679086,82
2011,others,3447972354,18
2012,copper,14630686732,80
2012,others,3583968218,20
2013,copper,15244038840,79
2013,others,4051281128,21
2014,copper,14703374241,78
2014,others,4251484600,22
2015,copper,13155922363,78
2015,others,3667286912,22
"
export <- read_csv(raw_export)

# export <- export |>
#   mutate(product = factor(
#     product,
#     levels = c("copper", "others"),
#     labels = c("Copper", "Other goods")))

export |> mutate(product = factor(
  product,
  levels = c("copper", "others"),
  labels = c("Copper", "Other goods"))) -> export
```

<!--
```{r exports-line-plot, fig.cap = "Exports to China", fig.dim = c(9, 6)}
ggplot(export, aes(x = year, y = export, color = product)) +
  geom_line(size = 1.5) + geom_point(size = 3) +
  scale_x_continuous(breaks = min(export$year):max(export$year)) +
  labs(title = "Exports to China, USD", subtitle = "Source: Observatory of economics") +
  labs(x = "Year", y = "USD") +
  theme(
    legend.title = element_blank(),
legend.position = "bottom",
    legend.direction = "horizontal") +
  scale_color_manual(values = c("#AA3939", "#7A9F35", "#226666"))
```
-->

<!--
```{r exports-area-plot, fig.cap = "Exports to China", fig.dim = c(9, 6)}
ggplot(export, aes(x = year, y = export, fill = product)) +
  geom_area(alpha = 0.7) +
  scale_x_continuous(breaks = min(export$year):max(export$year)) +
  labs(title = "Exports to China, USD", subtitle = "Source: Observatory of economics") +
  labs(x = "Year", y = "USD") +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.title = element_blank()) +
  scale_fill_manual(values = c("#E1B378","#5F9EA0"))
```
-->
